SWIDEA_SITE/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('ideas/', include("ideas.urls",namespace="ideas")),
    path('tools/', include("tools.urls",namespace="tools")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SWIDEA_SITE/ideas/urls.py
from django.urls import path
from .views import *

app_name = 'ideas'

urlpatterns = [
    path("",idea_list, name="idea_list"),
    path("create/",idea_create, name="idea_create"),
    path("detail/<int:pk>/",idea_detail, name="idea_detail"),
    path("update/<int:pk>/",idea_update, name="idea_update"),
    path("delete/<int:pk>/",idea_delete, name="idea_delete"),
    path('<int:pk>/update_interest/', update_interest, name='update_interest'),
    path('<int:pk>/star/', star_idea, name='star'),
    path('<int:pk>/unstar/', unstar_idea, name='unstar'),
]

SWIDEA_SITE/tools/urls.py
from django.urls import path
from .views import *

app_name = 'tools'

urlpatterns = [
    path("",tool_list, name="tool_list"),
    path("create/",tool_create, name="tool_create"),
    path("detail/<int:pk>/",tool_detail, name="tool_detail"),
    path("update/<int:pk>/",tool_update, name="tool_update"),
    path("delete/<int:pk>/",tool_delete, name="tool_delete"),
] 

SWIDEA_SITE/ideas/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import User
from tools.models import Tool
from django.utils import timezone

# Create your models here.

class Idea(models.Model):
    title = models.CharField(max_length=50)
    image = models.ImageField(upload_to="image/")
    content = models.CharField(max_length=255)
    interest = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(10)])
    tool = models.ForeignKey(Tool, on_delete=models.SET_NULL, null =True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    
class IdeaStar(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    idea = models.ForeignKey(Idea, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'idea')

SWIDEA_SITE/tools/models.py
from django.db import models

# Create your models here.
class Tool(models.Model):
    name = models.CharField(max_length=50, unique=True)
    kind = models.CharField(max_length=50)
    content = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name

SWIDEA_SITE/ideas/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render,redirect, get_object_or_404
from django.http import JsonResponse
from .models import Idea, IdeaStar
from  .form import IdeaForm
from django.db.models import Count

# Create your views here.
def idea_list(request):
    sort = request.GET.get('sort', 'created')

    if sort == 'name':
        ideas = Idea.objects.all().order_by('title')
    elif sort == 'created': 
        ideas = Idea.objects.all().order_by('-id')
    elif sort == 'like':
        ideas = Idea.objects.annotate(star_count=Count('ideastar')).order_by('-star_count')    
        
    starred_ideas = []
    if request.user.is_authenticated:
        starred_ideas = Idea.objects.filter(ideastar__user=request.user)
    context ={
        "ideas" : ideas,
        'starred_ideas': starred_ideas
    }

    return render (request, "ideas/idea_list.html",context)

def idea_detail(request, pk):
    idea = Idea.objects.get(id=pk)
    if request.user.is_authenticated:
        is_starred = IdeaStar.objects.filter(user=request.user, idea=idea).exists()
    context = {
        "idea" : idea,
        'is_starred': is_starred,
    }
    return render(request,"ideas/idea_detail.html",context)

def idea_create(request):
    if request.method == 'POST':
        form = IdeaForm(request.POST,request.FILES)
        if form.is_valid():
            idea = form.save()
            return redirect("ideas:idea_detail",pk=idea.pk)
    else:
        form = IdeaForm()
    
    return render(request,"ideas/idea_create.html",{"form":form})

def idea_update(request,pk):
    idea = get_object_or_404(Idea,id = pk)
    if request.method == 'POST':
        form = IdeaForm(request.POST,request.FILES,instance=idea)
        if form.is_valid():
            idea = form.save()
            return redirect("ideas:idea_detail",pk=idea.pk)
    else:
        form = IdeaForm(instance=idea)
    
    return render(request,"ideas/idea_create.html",{"form":form})

def idea_delete(request,pk):
    if request.method =="POST":
        idea = Idea.objects.get(id=pk)
        idea.delete()
    
    return redirect("ideas:idea_list")

def update_interest(request, pk):
    if request.method == "POST":
        idea = Idea.objects.get(id=pk)
        action = request.POST.get("action")

        if action == "increase":
            idea.interest += 1
        elif action == "decrease":
            idea.interest -= 1

        idea.save()
        return JsonResponse({"interest": idea.interest})
    
@login_required
def star_idea(request, pk):
    idea = get_object_or_404(Idea, id=pk)
    IdeaStar.objects.get_or_create(user=request.user, idea=idea)
    return redirect('ideas:idea_list')

@login_required
def unstar_idea(request, pk):
    idea = get_object_or_404(Idea, id=pk)
    IdeaStar.objects.filter(user=request.user, idea=idea).delete()
    return redirect('ideas:idea_list')

SWIDEA_SITE/tools/views.py
from django.shortcuts import render,redirect, get_object_or_404
from .models import Tool
from  .form import ToolForm
from ideas.models import Idea

# Create your views here.
def tool_list(request):
    tools = Tool.objects.all()
    context ={
        "tools" : tools
    }
    return render (request, "tools/tool_list.html",context)

def tool_detail(request, pk):
    tool = Tool.objects.get(id=pk)
    related_ideas = Idea.objects.filter(tool=tool)
    context = {
        "tool" : tool,
        "related_ideas": related_ideas,
    }
    return render(request,"tools/tool_detail.html",context)

def tool_create(request):
    if request.method == 'POST':
        form = ToolForm(request.POST,request.FILES)
        if form.is_valid():
            tool = form.save()
            return redirect("tools:tool_detail",pk=tool.pk)
    else:
        form = ToolForm()
    
    return render(request,"tools/tool_create.html",{"form":form})

def tool_update(request,pk):
    tool = get_object_or_404(Tool,id = pk)
    if request.method == 'POST':
        form = ToolForm(request.POST,request.FILES,instance=tool)
        if form.is_valid():
            tool = form.save()
            return redirect("tools:tool_detail",pk=tool.pk)
    else:
        form = ToolForm(instance=tool)
    
    return render(request,"tools/tool_create.html",{"form":form})

def tool_delete(request,pk):
    if request.method =="POST":
        tool = Tool.objects.get(id=pk)
        tool.delete()
    
    return redirect("tools:tool_list")

SWIDEA_SITE/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <title>{% block title %}My SW Idea Manage{% endblock %}</title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
    />
    <style>
      body {
        align-items: center;    
        min-height: 100vh;       
        margin: 0;
        background-color: #111;
        color: #fff;
        background-repeat: no-repeat;
      }

      .container {
        background-color: #222;
        padding: 30px;
        border-radius: 15px;
        margin-top: 40px;
      }

      .idea-sort-link {
        margin-bottom: 20px;
        text-align: center;
        display: flex;
      }

      .navbar {
        background-color: #222;
        padding: 20px 30px;
        display: flex;
        justify-content: space-between;
        align-items: center;
      }

      .navbar-brand {
        color: #0ff;
        font-size: 1.5rem;
        font-weight: bold;
        text-decoration: none;
      }

      .nav-menu, .nav-link {
        list-style: none; 
        margin: 0;
        padding: 0;
        display: flex;
        gap: 20px;
        color: #0ff;
        text-decoration: none;
        font-weight: 500;
      }

      h2 {
      text-align: center;
      margin-bottom: 30px;
      }

      .row{
        display: grid;
        grid-template-columns: repeat(3, 1fr); 
        gap: 20px;
        margin: 20px 0;
        flex: row;
        text-align: center;
        height: auto;
      }

      .card {
        height: 100%;
        display: flex;
        flex-direction: column;
        justify-content: space-between;
      }

      .card-img-top {
      height: 300px;
      object-fit: contain;
      }

      .btn-group {
        display: flex;
        gap: 10px;
        width: 250px;
        margin-top: 20px;
      }

      p {
        margin: 0;
      }

      .detail-wrapper {
        display: flex;
        gap: 40px;
        align-items: flex-start;
        justify-content: center;
        margin-top: 30px;
        flex-wrap: wrap;
      }

      .image-section {
        flex: 1 1 300px;
        text-align: center;
      }

      .detail-image {
        max-width: 300px;
        width: 100%;
        height: auto;
        border-radius: 10px;
      }

      .info-section {
        flex: 1 1 400px;
      }

      .tool-list{
        padding-left: 0;
        list-style: none; 
      }

      .tool-link{
        color: rgb(255, 255, 255);  
        text-decoration: none;     
        padding-left: 0;      
        cursor: pointer;
      }

      .card-link{
        color: rgb(21, 0, 255);  
        text-decoration: none;     
        padding-left: 0;      
        cursor: pointer;
      }
      
      .tool-link:hover,.card-link:hover {
        text-decoration: none; 
        color: #0ff;
      }

      .tool-item {
        margin-top: 20px;
        border-top: 1px solid #ddd;   
        border-bottom: 1px solid #ddd;
        padding: 1rem 0;              
        }

        .idea-card {
          position: relative;
        }

        .star-icon-list {
          position: absolute;
          top: 10px;
          right: 10px;
          font-size: 20px;
          text-decoration: none;
          color: gold;
        }

        .star-icon-detail {
          position: relative;
          font-size: 20px;
          text-decoration: none;
          color: gold;
        }
      .star-wrapper {
        text-align: right;
      }    

    </style>
  </head>
  <body>
    <nav class="navbar">
      <a class="navbar-brand" href="{% url 'ideas:idea_list' %}">My SW Idea Manage</a>
      <div>
        <ul class="nav-menu" >
          <li>
            <a class="nav-link" href="{% url 'ideas:idea_create' %}">아이디어 등록</a>
          </li>
          <li>
            <a class="nav-link" href="{% url 'ideas:idea_list' %}">아이디어 관리</a>
          </li>
          <li>
            <a class="nav-link" href="{% url 'tools:tool_create' %}">개발툴 등록</a>
          </li>
          <li>
            <a class="nav-link" href="{% url 'tools:tool_list' %}">개발툴 관리</a>
          </li>
        </ul>
      </div>
    </nav>

    <div class="container">{% block content %} {% endblock %}</div>
  </body>
</html>

SWIDEA_SITE/templates/ideas/idea_create.html
{% extends "base.html" %} 
{% block content %}
<h2>Idea Register</h2>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %} {{ form.as_p }}
  <button type="submit" style="padding: 8px 16px; background-color: gray; color: white; text-decoration: none; border-radius: 5px; margin-right: 10px; font-size: 14px;">SUBMIT</button>
</form>
{% endblock %}

SWIDEA_SITE/templates/ideas/idea_detail.html
{% extends "base.html" %}
{% block content %}
<h2 class="title-center">Idea Detail</h2>
    {% if user.is_authenticated %}
      <div class="star-wrapper">
        {% if is_starred %}
          <a href="{% url 'ideas:unstar' idea.id %}" class="star-icon-detail">★ 찜 취소</a>
        {% else %}
          <a href="{% url 'ideas:star' idea.id %}" class="star-icon-detail">☆ 찜하기</a>
        {% endif %}
      </div>
    {% endif %}

<div class="detail-wrapper">
  <div class="image-section">
    <img src="{{ idea.image.url }}" alt="image" class="detail-image" />
  </div>

  <div class="info-section">
    <h3>{{ idea.title }}</h3>
    <p>예상 개발툴: {{ idea.tool.name }}</p>
    <p>아이디어 관심도: {{ idea.interest }}</p>
    <p>{{ idea.content }}</p>

    <div class="btn-group">
      <a href="{% url 'ideas:idea_update' idea.id %}" style="padding: 8px 16px; background-color: gray; color: white; text-decoration: none; border-radius: 5px; margin-right: 10px; font-size: 14px;">수정</a>
      <a href="{% url 'ideas:idea_list' %}" style="padding: 8px 16px; background-color: rgb(0, 30, 255); color: white; text-decoration: none; border-radius: 5px; margin-right: 10px; font-size: 14px;">목록</a>
      <form action="{% url 'ideas:idea_delete' idea.id %}" method="POST" style="display: inline;">
        {% csrf_token %}
        <button type="submit" onclick="return confirm('정말 삭제하시겠습니까?')" style="padding: 8px 16px; background-color: crimson; color: white; border: none; border-radius: 5px; cursor: pointer; font-size: 14px;">삭제</button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

SWIDEA_SITE/templates/ideas/idea_list.html
{% extends "base.html" %}
{% block content %}
<h2>Idea List</h2>
  <span class="idea-sort-link">
    <a href="?sort=name" style="margin-right: 10px; text-decoration: none; color: inherit;"> 🔤이름순</a>
    <a href="?sort=created" style="margin-right: 10px; text-decoration: none; color: inherit;">🕒 등록일순</a>
    <a href="?sort=like" style="text-decoration: none; color: inherit;">⭐ 찜하기순</a>
  </span>

<div class="row">
  {% for idea in ideas %}
  <div>
    <div class="card">
      <img src="{{ idea.image.url }}" class="card-img-top" alt="..." />
      {% if user.is_authenticated %}
        {% if idea in starred_ideas %}
          <a href="{% url 'ideas:unstar' idea.id %}" class="star-icon-list">★</a>
        {% else %}
          <a href="{% url 'ideas:star' idea.id %}" class="star-icon-list">☆</a>
        {% endif %}
      {% endif %}
      <div class="card-body">
        <a href="{% url 'ideas:idea_detail' idea.id %}" class="card-link">{{ idea.title }}</a>
        <p></p>
        개발 툴: 
        <a href="{% url 'tools:tool_detail' idea.tool.id %}" style="text-decoration: none; color: inherit; padding: 30px;">
          {{ idea.tool.name }}
        </a>
        <p>
        아이디어 관심도:
        <button onclick="updateInterest('{{ idea.id }}', 'decrease')">➖</button>
        <span id="interest-{{ idea.id }}">{{ idea.interest }}</span>
        <button onclick="updateInterest('{{ idea.id }}', 'increase')">➕</button>
      </p>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
<script>
  function updateInterest(ideaId, action) {
    fetch(`/ideas/${ideaId}/update_interest/`, {
      method: "POST",
      headers: {
        "X-CSRFToken": "{{ csrf_token }}",
        "Content-Type": "application/x-www-form-urlencoded"
      },
      body: `action=${action}`
    })
    .then(response => response.json())
    .then(data => {
      document.getElementById(`interest-${ideaId}`).innerText = data.interest;
    });
  }
</script>
{% endblock %}

SWIDEA_SITE/templates/ideas/idea_update.html
{% extends "base.html" %}
{% block content %}
<h2>Idea Detail Update</h2>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %} {{ form.as_p }}
  <button type="submit" style="padding: 8px 16px; background-color: gray; color: white; text-decoration: none; border-radius: 5px; margin-right: 10px; font-size: 14px;">SUBMIT</button>
</form>
{% endblock %}

SWIDEA_SITE/templates/tools/tool_create.html
{% extends "base.html" %} 
{% block content %}
<h2>Tool Register</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %} {{ form.as_p }}
    <button type="submit" style="padding: 8px 16px; background-color: gray; color: white; text-decoration: none; border-radius: 5px; margin-right: 10px; font-size: 14px;">SUBMIT</button>
</form>
{% endblock %}

SWIDEA_SITE/templates/tools/tool_detail.html
{% extends 'base.html' %}

{% block content %}
<h2>DevTool Detail</h2>
<p>선택하신 개발툴의 상세정보입니다.</p>

    <h3>{{ tool.name }}</h3>
    <p><strong>분류:</strong> {{ tool.kind }}</p>
    <p><strong>설명:</strong> {{ tool.content }}</p>

    <div class="btn-group">
    <a href="{% url 'tools:tool_update' tool.id %}" style="padding: 8px 16px; background-color: gray; color: white; text-decoration: none; border-radius: 5px; margin-right: 10px; font-size: 14px;">수정</a>
    <a href="{% url 'tools:tool_list' %}" style="padding: 8px 16px; background-color: rgb(0, 30, 255); color: white; text-decoration: none; border-radius: 5px; margin-right: 10px; font-size: 14px;">목록</a>
    <form action="{% url 'tools:tool_delete' tool.id %}" method="POST" style="display: inline;">
        {% csrf_token %}
        <button type="submit" onclick="return confirm('정말 삭제하시겠습니까?')" style="padding: 8px 16px; background-color: crimson; color: white; border: none; border-radius: 5px; cursor: pointer; font-size: 14px;">삭제</button>
    </form>
    </div>
    <hr>
    <h3>이 개발툴을 사용하는 아이디어</h3>
    {% if related_ideas %}
    <ul>
        {% for idea in related_ideas %}
        <li>
            <a href="{% url 'ideas:idea_detail' idea.id %}" style="text-decoration: none; color: inherit; margin: 20px;">
            {{ idea.title }}
            </a>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>이 개발툴을 사용하는 아이디어가 아직 없습니다.</p>
    {% endif %}
{% endblock %}

SWIDEA_SITE/templates/tools/tool_list.html
{% extends 'base.html' %}

{% block content %}
<h2>DevTool List</h2>
<p>개발툴 목록을 확인하세요. 사용하실 개발툴을 선택하시면 상세 페이지로 이동합니다.</p>

    <ul class="tool-list">
    {% for tool in tools %}
        <li class="tool-item">
        <a href="{% url 'tools:tool_detail' tool.id %}" class="tool-link">
            <strong>{{ tool.name }}</strong> - {{ tool.kind }}<br>
            {{ tool.content|truncatewords:20 }}
        </a>
        </li>
    {% endfor %}
    </ul>
{% endblock %}

SWIDEA_SITE/templates/tools/tool_update.html
{% extends "base.html" %}
{% block content %}
<h2>Tool Detail Update</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %} {{ form.as_p }}
    <button type="submit" style="padding: 8px 16px; background-color: gray; color: white; text-decoration: none; border-radius: 5px; margin-right: 10px; font-size: 14px;">SUBMIT</button>
</form>
{% endblock %}