myMovieReviews/reviews/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', review_list, name='review_list'),
    path("<int:pk>/", review_detail, name='review_detail'),
    path("create/", review_create, name='review_create'),
    path("<int:pk>/update/", review_update, name='review_update'),
    path("<int:pk>/delete/",review_delete, name='review_delete'),
]

myMovieReviews/reviews/models.py
from django.db import models

# Create your models here.
class Review(models.Model):
    GENRE_CHOICES = [
        ('DR', '드라마'),
        ('CM', '코미디'),
        ('AC', '액션'),
        ('RM', '로맨스'),
        ('TH', '스릴러'),
        ('HR', '공포'),
        ('SF', 'SF'),
        ('AN', '애니메이션'),
        ('DC', '다큐멘터리'),
        ('ET', '기타'),
    ]
    title = models.CharField(max_length=50)
    poster = models.ImageField(upload_to="poster/")
    release_year = models.PositiveIntegerField()
    director = models.CharField(max_length=50)
    cast = models.CharField(max_length=100)
    genre = models.CharField(max_length=2, choices= GENRE_CHOICES)
    rating = models.DecimalField(max_digits=2, decimal_places=1)
    running_time = models.PositiveIntegerField(help_text="단위: 분")
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self): # 인스턴스 출력시 가독성 높이기
        return f"{self.title} ({self.release_year})"

myMovieReviews/reviews/forms.py
from django import forms
from .models import Review

class ReviewForm(forms.ModelForm): # 자동으로 폼 만들기
    class Meta:
        model = Review
        fields = '__all__'

myMovieReviews/reviews/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Review
from .forms import ReviewForm  

# Create your views here.
def review_list(request):
    sort = request.GET.get('sort', 'rating') # 기본값: 별점순
    if sort == 'rating':
        reviews = Review.objects.all().order_by('-rating')
    elif sort == 'year':
        reviews = Review.objects.all().order_by('-release_year')
    else:
        reviews = Review.objects.all().order_by('-created_at')

    return render(request, 'reviews/list.html', {'reviews': reviews})

def review_detail(request, pk):
    review = get_object_or_404(Review, pk=pk)
    hours = review.running_time // 60
    minutes = review.running_time % 60  
    
    return render(request, 'reviews/detail.html', {
        'review': review,
        'hours': hours,
        'minutes': minutes,
    })

def review_create(request): 
    if request.method == "POST" :
        form = ReviewForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('review_list')
    else:
        form = ReviewForm()
    
    return render(request, 'reviews/create.html', {"form": form})

def review_update(request, pk):
    review = get_object_or_404(Review, pk=pk)
    if request.method == "POST":
        form = ReviewForm(request.POST, request.FILES, instance=review)
        if form.is_valid():
            form.save()
            return redirect('review_detail', pk=pk)
    else:
        form = ReviewForm(instance=review)

    return render(request, 'reviews/create.html', {"form": form})

def review_delete(request, pk):
    if request.method == "POST":
        review = Review.objects.get(id=pk)
        review.delete()

    return redirect("/reviews/")

myMovieReviews/reviews/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>리뷰 게시판</title>
    <style>
        body {
            font-family: sans-serif;
            margin : 0 30px;
        }

        h1 {
            color: orange;
        }

        .review-container {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-between;
            gap: 24px;
        }

        .review-card {
            width: 200px;
            padding: 8px;
            background-color: #f3f3f3;
            border-radius: 10px;
            text-align: center;
        }

        .review-card img {
            width: 100%;
            height: 280px;
            object-fit: cover;
            border-radius: 8px;
        }

        .review-card h3 {
            margin: 12px 0 6px;
        }

        .review-card p {
            margin: 4px 0;
            color: #555;
        }

        .add-btn {
            float: right;
            margin-bottom: 20px;
        }
    </style>
</head>
<body>
    <div style="display: flex; justify-content: space-between; align-items: center;">
        <a href="{% url 'review_list' %}" style="text-decoration: none; color: orange; font-size: 20px;">
            <h1>my <span style="color:crimson">Movie</span> reviews</h1>
        </a>

        <a href="{% url 'review_create' %}" style="text-decoration: none;">
            <h2 style="color: black; margin: 0;">리뷰 작성</h2>
        </a>
    </div>
    {% block content %}
    {% endblock %}
</body>
</html>

myMovieReviews/reviews/templates/reviews/create.html
{% extends 'base.html' %}

{% block content %}
<form method="POST" enctype="multipart/form-data"> <!-- 이미지를 전송을 위한 인코딩 방식 설정-->
    {% csrf_token %}
    {{ form.as_p }} <!-- <p> 태그로 알아서 감싸줌  -->
    <button type="submit">저장</button>
</form>
{% endblock %}

myMovieReviews/reviews/templates/reviews/detail.html
{% extends 'base.html' %}

{% block content %}
<div style="width: 80%; margin: 0 auto;">
    <h2>{{ review.title }}</h2>

    <div style="display: flex; gap: 20px;">
        <!-- 포스터 -->
        <img src="{{ review.poster.url }}" alt="{{ review.title }}" style="width: 200px; height: auto;">

        <!-- 영화 정보 -->
        <div>
            <p><strong>개봉년도:</strong> {{ review.release_year }}년</p>
            <p><strong>감독:</strong> {{ review.director }}</p>
            <p><strong>주연:</strong> {{ review.cast }}</p>
            <p><strong>장르:</strong> {{ review.get_genre_display }}</p>
            <p><strong>별점:</strong> {{ review.rating }}</p>
            <p><strong>러닝타임:</strong> {{ hours }}시간 {{ minutes }}분</p>

        </div>
    </div>

    <!-- 리뷰 본문 -->
    <div style="margin-top: 30px;">
        <p>{{ review.content }}</p>
    </div>

    <!-- 수정/삭제 버튼 -->
    <div style="margin-top: 20px; text-align: right;">

            <a href="{% url 'review_update' review.id %}" style="padding: 8px 16px; background-color: gray; color: white; text-decoration: none; border-radius: 5px; margin-right: 10px; font-size: 14px;">
            수정
            </a>
            <form action="{% url 'review_delete' review.id %}" method="POST" style="display: inline;">
                {% csrf_token %}
                <button type="submit" onclick="return confirm('정말 삭제하시겠습니까?')" style="padding: 8px 16px; background-color: crimson; color: white; border: none; border-radius: 5px; cursor: pointer; font-size: 14px;">
                    삭제
                </button>
            </form>
    </div>
</div>
{% endblock %}

myMovieReviews/reviews/templates/reviews/list.html
{% extends 'base.html' %}

{% block content %}

    <div style="margin-bottom: 20px;">
        <a href="?sort=rating" style="margin-right: 10px; text-decoration: none; color: inherit;">⭐ 별점순</a>
        <a href="?sort=created" style="margin-right: 10px; text-decoration: none; color: inherit;">🕒 등록일순</a>
        <a href="?sort=year" style="text-decoration: none; color: inherit;">📅 최신개봉순</a>
    </div>

    <div class="review-container">
        {% for review in reviews %}
            <div class="review-card">
                <a href="/reviews/{{ review.id }}/" style="text-decoration: none; color: inherit;">
                    {% if review.poster %}
                        <img src="{{ review.poster.url }}" alt="{{ review.title }} 포스터">
                    {% else %}
                        <div style="width: 100%; height: 280px; background-color: #ddd; display: flex; align-items: center; justify-content: center; border-radius: 8px;">
                            <span>이미지 없음</span>
                        </div>
                    {% endif %}
                    <h3>{{ review.title }}</h3>
                    <p>개봉년도 {{ review.release_year }}년</p>
                    <p>장르 {{ review.get_genre_display }}</p>
                    <p>별점 {{ review.rating }}</p>
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock %}